// Session token for the per-user dub STT worker (modal/dub_worker.py).
//
// The worker (vendored from realtime-tts/worker-stt-prod) authenticates with an HMAC session token in exactly the
// format the realtime-tts gateway mints: base64url(JSON {id, exp}) + "." + base64url(HMAC-SHA256(secret, payload)),
// where exp is in MILLISECONDS since the epoch. For a per-user deployment the secret is that deployment's own
// MODAL_SESSION_SECRET (generated by the deployment manager), so a token for one user's worker is useless anywhere else.
import { createHmac } from 'node:crypto';

export const DUB_TOKEN_TTL_MS = 10 * 60_000;

export function mintDubSessionToken(secret: string, id: string, now: number = Date.now(), ttlMs: number = DUB_TOKEN_TTL_MS): string {
  if (!secret) throw new Error('cannot mint a dub session token without a secret');
  const payload = Buffer.from(JSON.stringify({ id, exp: now + ttlMs })).toString('base64url');
  const sig = createHmac('sha256', secret).update(payload).digest('base64url');
  return `${payload}.${sig}`;
}
